#########################################操作列表#########################################
# [connect]|<服务器>                                     ——切换服务器
# [player]|<命令>                                       ——玩家执行命令
# [player_op]|<命令>                                    ——玩家以op权限执行命令(注意保护)
# [console]|<命令>                                      ——后台执行命令
# [broadcast]|<消息>                                    ——发送全服消息
# [message]|<消息>                                      ——发送消息给玩家
# [actionbar]|<消息>                                    ——发送操作栏消息
# [bossbar]|<消息>|<颜色>|<样式>|<进度>|<显示时间>          ——给玩家发送一个限时boss血条
# [title]|<主标题>|<副标题>|<淡入时间>|<停留时间>|<淡出时间>  ——给玩家发送一个标题消息
# [chat]|<消息>                                         ——以玩家身份发送消息
# [sound_bukkit]|<音效ID>|<音量>|<音调>                   ——给玩家发送一个bukkit音效ID的音效
# [sound_minecraft]|<音效ID>|<音量>|<音调>                ——给玩家发送一个minecraft音效ID的音效
# [menu]|<菜单>                                         ——打开自定义菜单
# [close]                                              ——关闭菜单
#########################################操作列表#########################################
# 任意操作后面增加 <delay=[Tick]> 可以延迟操作
# 例如: [player]|say BaiShenYaoDog<delay=5>
#########################################操作列表#########################################
#
#########################################PAPI变量#########################################
# %mhdftools_nick_name%               ——匿名名称(如果没有,则返回默认ID)
# %mhdftools_money_amount%            ——经济数量
# %mhdftools_money_name%              ——货币名称
#########################################PAPI变量#########################################

# 配置文件版本号(请勿修改)
configVersion: "${project.version}"

# 调试模式
debug: false

# bStats https://bstats.org/plugin/bukkit/MHDF-Tools/24887
bStats: true

# 群组设置
# 群组模式下必须使用redis缓存
bungeeCordSettings:
  # 开关
  enable: false
  # 自动重试
  autoTry:
    # 延迟(单位: ticks)
    delay: 10
    # 最大重试次数
    maxTimes: 5

# 数据库设置
databaseSettings:
  # 数据库类型
  # (mysql h2)
  type: "h2"
  # MySQL数据库设置
  mysql:
    # 地址
    host: "127.0.0.1:3306"
    # 数据库
    database: "mhdf_tools"
    # 用户
    user: "root"
    # 密码
    password: "root"
  # H2数据库设置
  h2:
    # 数据库文件
    file: "database.db"

# 缓存设置
cacheSettings:
  # 存储类型
  # (map redis)
  type: "map"
  # 服务池ID
  # 只有相同 服务池ID 服务器才会互相同步缓存
  server: ""
  # Redis数据库设置
  redis:
    # 地址
    host: "localhost:6379"
    # 用户
    user: ""
    # 密码
    password: ""

# 网络请求设置
httpSettings:
  # 代理
  proxy:
    # 开关
    enable: false
    # 类型
    # HTTP SOCKS
    type: "HTTP"
    # 地址
    host: "127.0.0.1"
    # 端口
    port: 7890

# 随机传送
randomTeleportSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "rtp"
    - "randomteleport"
  # 黑名单世界
  blackWorld: [ ]
  # 黑名单方块
  blackBlock:
    - "WATER"
    - "LAVA"
  # 默认
  default:
    # 权重
    weight: 0
    # 最小
    min: 1000
    # 最大
    max: 1500
    # 延迟
    delay:
      # 开关
      enable: true
      # 时间(单位: 秒)
      time: 60
  # 拥有 mhdftools.group.randomteleport.<名字> 权限的提示
  # 例如 mhdftools.group.randomteleport.vip
  # vip:
    # 权重
    # weight: 1
    # 最小
    # min: 1000
    # 最大
    # max: 1500
    # 延迟
    # delay:
    #   # 开关
    #   enable: true
    #   # 时间(单位: 秒)
    #   time: 60

# 崩溃玩家客户端
crashSettings:
  # 开关
  enable: true
  # 默认崩溃模式
  # (explosion invalidTeleport invalidParticle)
  defaultType: "explosion"
  # 命令
  commands:
    - "crash"

# 击退玩家
knockBackSettings:
  #开关
  enable: true
  #击退的设置
  vector:
    x: 0.75
    y: 0.5
    z: 0.75
  # 命令
  commands:
    - "kb"
    - "knockback"

# 查看在线列表
listSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "list"

# 飞行
flySettings:
  # 开关
  enable: true
  # 自动开启
  autoEnable:
    # 加入服务器
    joinServer: true
    # 切换世界
    changeWorld: true
    # 重生
    respawn: true
  # 自动关闭
  autoDisable:
    # 掉血
    takeHealth: false
    # 世界列表
    worldList:
      - "awa"
  # 飞行强制关闭坠落倒计时
  fallTime: 5
  # 命令
  commands:
    - "fly"
  # 限时飞行命令
  flytimeCommands:
    - "flytime"

# 隐身
vanishSettings:
  # 开关
  enable: true
  # 从补全中移除
  tabRemove: true
  # 命令
  commands:
    - "vanish"

# 更好的关服
stopSettings:
  # 开关
  enable: true
  # 确认关服
  confirm: true
  # 关闭服务器的时候保存存档
  autoSave: true
  # 默认倒计时(-1关闭)
  defaultCountdown: 5
  # 命令
  commands:
    - "stop"

# 传送到玩家
tpaSettings:
  # 开关
  enable: true
  # 延迟
  delay: 60
  # 命令
  commands:
    - "tpa"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 传送玩家过来
tpahereSettings:
  # 开关
  enable: true
  # 延迟
  delay: 60
  # 命令
  commands:
    - "tpahere"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 自定义菜单
customMenuSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "menu"

# 家系统
homeSettings:
  # 开关
  enable: true
  # 默认最大家数量
  # 可以通过 mhdftools.commands.home.max.<数量> 自定义
  defaultMax: 10
  # 命令
  commands:
    - "home"
  # 设置家命令
  sethomeCommands:
    - "sethome"
  # 删除家命令
  delhomeCommands:
    - "delhome"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 返回死亡点
backSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "back"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 返回传送前的位置
tpbackSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "tpback"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 出生点
spawnSettings:
  # 开关
  enable: true
  # 自动传送
  autoTeleport:
    # 复活
    respawn: false
    # 加入服务器
    join: false
  # 位置
  location:
    # 服务器
    server: "无"
    # 世界
    world: "world"
    # x轴坐标
    x: 0.0
    # y轴坐标
    y: 60.0
    # z轴坐标
    z: 0.0
    # yaw角度
    yaw: 0.0
    # pitch角度
    pitch: 0.0
  # 命令
  commands:
    - "spawn"
  setspawnCommands:
    - "setspawn"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 匿名
nickSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "nick"

# 查询IP信息
ipSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "ip"
    - "ipinfo"

# 切换游戏模式
gamemodeSettings:
  # 开关
  enable: true
  # 游戏模式
  gamemode:
    # 生存
    survival:
      - "survival"
      - "生存"
      - "0"
    # 创造
    creative:
      - "creative"
      - "创造"
      - "1"
    # 冒险
    adventure:
      - "adventure"
      - "冒险"
      - "2"
    # 旁观
    spectator:
      - "spectator"
      - "旁观"
      - "3"
  # tab补全
  tabCompleter:
    - "生存"
    - "创造"
    - "冒险"
    - "旁观"
  # 命令
  commands:
    - "gamemode"
    - "gm"

# 回到床的位置
bedSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "bed"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 自杀
suicideSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "suicide"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 帽子
hatSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "hat"

# 传送点系统
warpSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "warp"
  # 设置传送点命令
  setwarpCommands:
    - "setwarp"
  # 删除传送点命令
  delwarpCommands:
    - "delwarp"
  # 黑名单世界
  blackWorld:
    - "pvp"

# 快速使用
fastUseSettings:
  # 开关
  enable: true
  # 潜影盒(权限: mhdftools.fastuse.shulkerbox)
  shulkerBox: true
  # 末影箱(权限: mhdftools.fastuse.enderchest)
  enderChest: true
  # 工作台(权限: mhdftools.fastuse.craftingtable)
  craftingTable: true

# 修复1.13+三叉戟复制漏洞
tridentDupeFixSettings:
  # 开关
  enable: true

# 修复1.21+收纳袋崩服漏洞
bundleFixSettings:
  # 开关
  enable: true

# 快速调节时间
fastChangeTimeSettings:
  # 开关
  enable: true
  # 时间
  time:
    # 自定义命名
    早上:
      # 时间
      time: 1000
      # 命令
      commands:
        - "day"
    # 自定义命名
    晚上:
      # 时间
      time: 13000
      # 命令
      commands:
        - "night"

# 快速调节天气
fastChangeWeatherSettings:
  # 开关
  enable: true
  # 时间
  weather:
    # 自定义命名
    晴天:
      # 下雨
      storm: false
      # 打雷
      thunder: false
      # 命令
      commands:
        - "sun"

# 虚假调节时间
fakeChangeTimeSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "fakeChangeTime"

# 背包查看
invseeSettings:
  # 开关
  enable: true
  # 命令
  commands:
    - "inv"
    - "invsee"

# 屏蔽
ignoreSettings:
  # 开关
  enable: true
  # 禁止屏蔽列表
  # 绕过权限: mhdftools.bypass.ignore.blacklist
  blacklist:
    - "BaiShenYao_Dog"
  # 命令
  commands:
    - "ignore"

# 聊天
chatSettings:
  # 开关
  enable: true
  # 聊天延迟设置
  # 绕过权限: mhdftools.bypass.chat.delay
  delay:
    # 开关
    enable: true
    # 延迟
    delay: 3
  # 禁止刷屏设置
  # 绕过权限: mhdftools.bypass.chat.spam
  spam:
    # 开关
    enable: true
  # 替换词设置
  # 绕过权限: mhdftools.bypass.chat.replaceWord
  replaceWord:
    # 开关
    enable: true
    # 替换
    replace:
      - # 文本
        word:
          - "傻逼"
        # 替换方式
        # word  ——替换目标词
        # line  ——替换整句
        type: "line"
        # 替换后的文本
        # replaceWord: "喵"
        # 替换后的句子(随机选择)
        lineList:
          - "主人,我错惹喵~"
  # 展示物品设置
  showItem:
    # 开关
    enable: true
    # 格式
    format: "&b[&f{name} &ax{amount}&b]"
    # 关键词
    word:
      - "[i]"
  # 私聊设置
  msg:
    # 开关
    enable: true
    # 命令
    commands:
      - "w"
      - "msg"
      - "tell"
    # 回复
    replyCommands:
      - "r"
      - "reply"
  # at设置
  at:
    # 开关
    enable: true
    # 匹配正则 @{
    patternFormat: "@?{at}"
    # 全体消息的关键词
    # 全体消息权限: mhdftools.chat.all
    allMessage:
      - "all"
  # 格式设置
  # 绕过颜色限制权限: mhdftools.bypass.chat.color
  # miniMessage格式限制权限: mhdftools.bypass.chat.minimessage
  format:
    # 开关
    enable: true
    # 默认
    default:
      # 权重
      weight: 0
      # 格式
      format: "&f[玩家] {player}&f: {message}"
    # 拥有 mhdftools.group.chatformat.<名字> 权限的提示
    # 例如 mhdftools.group.chatformat.admin
    # admin:
      # 权重
      # weight: 1
      # 格式
      # format: "&c[管理] {player}&f: {message}"

# 经济系统
economySettings:
  # 开关
  enable: true
  # 默认货币数量
  default: 1000.0
  # 货币名称
  name: "金币"
  # 个人所得税
  personalIncomeTax:
    # 开关
    enable: true
    # 税率(单位: 百分比)
    rate: 0.05
  # 经济管理命令
  moneyadminCommands:
    - "moneyadmin"
    - "eco"
  # 查询余额命令
  moneyCommands:
    - "money"
  # 转账命令
  payCommands:
    - "pay"

# 进服消息
joinMessageSettings:
  # 开关
  enable: true
  # 移除消息
  removeMessage: false
  # 默认
  default:
    # 权重
    weight: 0
    # 提示消息
    message: "&a[+] &e{player}"
  # 拥有 mhdftools.group.joinmessage.<名字> 权限的提示
  # 例如 mhdftools.group.joinmessage.admin
  # admin:
    # 权重
    # weight: 1
    # 提示消息
    # message: "&a[+] &c{player}"

# 退服消息
quitMessageSettings:
  # 开关
  enable: true
  # 移除消息
  removeMessage: false
  # 默认
  default:
    # 权重
    weight: 0
    # 提示消息
    message: "&c[-] &e{player}"
  # 拥有 mhdftools.group.quitmessage.<名字> 权限的提示
  # 例如 mhdftools.group.quitmessage.admin
  # admin:
    # 权重
    # weight: 1
    # 提示消息
    # message: "&c[-] &c{player}"

# 事件操作
eventActionSettings:
  # 开关
  enable: true
  # 操作列表
  actionList:
    # 操作ID
    playerJoin:
      # 事件
      # =========================================
      # 玩家加入服务器 玩家退出服务器 玩家切换世界 玩家聊天
      # 玩家死亡 玩家复活 玩家移动 玩家传送 玩家破坏方块
      # 玩家放置方块
      # =========================================
      event: "玩家加入服务器"
      # 白名单世界
      # world:
      #  - "world"
      group:
        # 默认
        default:
          # 权重
          weight: 0
          # 操作
          action:
            - "[message]|&e主人早上好噢~"
        # 拥有 mhdftools.group.eventaction.<操作ID>.<名字> 权限的提示
        # 例如 mhdftools.group.eventaction.<操作ID>.admin
        # admin:
          # 权重
          # weight: 1
          # 操作
          # action:
          #   - "[message]|&e主人和我结婚吧~"

# 时间操作
timeActionSettings:
  # 开关
  enable: true
  # 操作列表
  actionList:
    # 自定义命名
    message:
      # 类型
      # =========================================
      # 定时操作 ——每多久操作一次
      # 定点操作 ——指定时间操作一次
      # =========================================
      type: "定时操作"
      # 时间(时:分:秒)
      time: "0:0:15"
      # 操作
      action:
        - "[broadcast]|&e谢谢主人喵,谢谢使用梦之工具喵~"
    # 自定义命名
    lunch:
      # 类型
      # =========================================
      # 定时操作 ——每多久操作一次
      # 定点操作 ——指定时间操作一次
      # =========================================
      type: "定点操作"
      # 时间(时:分:秒)
      time: "12:0:0"
      # 操作
      action:
        - "[broadcast]|&e主人喵,中午该吃饭咯~"

# motd设置
# {online}  ——当前在线
# {max}     ——最大在线
motdSettings:
  # 开关
  enable: true
  # 版本信息覆写
  # 可能导致无法查看服务器延迟
  version:
    # 开关
    enable: true
    # 版本名称(不支持RGB)
    name: "&a点击就送香香软软可爱橙汁汁"
  # 玩家数量
  players:
    # 开关
    enable: true
    # 假玩家数量
    fakePlayers:
      # 开关
      enable: true
      # 数量(数学表达式)
      amount: "{online}*2"
    # 假最大数量
    fakeMax:
      # 开关
      enable: true
      # 数量(数学表达式)
      amount: "5835"
    # 假玩家列表
    fakeSample:
      # 开关
      enable: true
      # 文本列表(不支持RGB)
      text:
        - "&b其实还可以送你一个可爱小猫娘噢~"
  # 简介
  description:
    - # 第一行
      line1: "<gradient:#F18989:#EAB5B5>骗你的,但是可以送你香香软软的杉杉噢</gradient>"
      # 第二行
      line2: "<gradient:#F1BB89:#EADFB5>怎么生气了,我错惹,橙汁给你行了吧www</gradient>"