name: MHDF-Tools
version: '${project.version}'
main: cn.chengzhiya.mhdftools.Main
api-version: '1.13'
folia-supported: true
authoendrs: [ BaiShenYao_Dog, Dg32z_, Araykal ]
softdepend: [ Vault, PlaceholderAPI, MythicMobs, CraftEngine ]
permissions:
  mhdftools.group.chatformat:
    description: 聊天分组权限
    default: false
  mhdftools.group.randomteleport:
    description: 随机传送分组权限
    default: false
  mhdftools.group.joinmessage:
    description: 进服消息分组权限
    default: false
  mhdftools.group.quitmessage:
    description: 进服消息分组权限
    default: false
  mhdftools.group.eventaction:
    description: 事件操作分组权限
    default: false

  mhdftools.bypass.chat.delay:
    description: 聊天延迟绕过
    default: op
  mhdftools.bypass.chat.spam:
    description: 聊天禁止刷屏绕过
    default: op
  mhdftools.bypass.chat.replaceWord:
    description: 聊天替换词绕过
    default: op
  mhdftools.bypass.ignore.blacklist:
    description: 屏蔽禁止屏蔽列表绕过
    default: op
  mhdftools.bypass.randomteleport.delay:
    description: 随机传送延迟绕过
    default: op

  mhdftools.chat.at.all:
    description: AT所有人
    default: op
  mhdftools.chat.color:
    description: 聊天颜色
    default: op
  mhdftools.chat.minimessage:
    description: 聊天miniMessage格式
    default: op

  mhdftools.commands.back:
    description: 返回死亡位置
    default: true
  mhdftools.commands.bed:
    description: 回到床的位置
    default: true
  mhdftools.commands.crash:
    description: 崩溃玩家客户端
    default: op
  mhdftools.commands.custommenu:
    description: 自定义菜单
    default: op
  mhdftools.commands.delhome:
    description: 删除家
    default: true
  mhdftools.commands.delwarp:
    description: 删除传送点
    default: op
  mhdftools.commands.fakechangetime:
    description: 虚假调节时间
    default: op
  mhdftools.commands.fastchangetime:
    description: 快速调节时间
    default: op
  mhdftools.commands.fastchangeweather:
    description: 快速调节天气
    default: op
  mhdftools.commands.fastchangeweather.other:
    description: 快速他人调节天气
    default: op
  mhdftools.commands.fly:
    description: 飞行
    default: op
  mhdftools.commands.fly.infinite:
    description: 无限飞行时长
    default: op
  mhdftools.commands.fly.give:
    description: 给予他人飞行
    default: op
  mhdftools.commands.flytime:
    description: 限时飞行
    default: op
  mhdftools.commands.gamemode:
    description: 修改玩家游戏模式
    default: op
  mhdftools.commands.gamemode.give:
    description: 修改他人游戏模式
    default: op
  mhdftools.commands.hat:
    description: 帽子
    default: true
  mhdftools.commands.home:
    description: 传送到指定家
    default: true
  mhdftools.commands.ignore:
    description: 屏蔽
    default: true
  mhdftools.commands.invsee:
    description: 查看背包
    default: op
  mhdftools.commands.ip:
    description: 查询IP信息
    default: op
  mhdftools.commands.knockback:
    description: 崩溃玩家客户端
    default: op
  mhdftools.commands.list:
    description: 查看在线列表
    default: true
  mhdftools.commands.lookitem:
    description: 展示物品
    default: true
  mhdftools.commands.mhdftools:
    description: 梦之工具主命令
    default: op
  mhdftools.commands.money:
    description: 查询余额
    default: true
  mhdftools.commands.money.other:
    description: 查询他人余额
    default: op
  mhdftools.commands.moneyadmin:
    description: 经济管理
    default: op
  mhdftools.commands.msg:
    description: 私聊
    default: op
  mhdftools.commands.nick:
    description: 修改匿名
    default: op
  mhdftools.commands.nick.give:
    description: 修改他人匿名
    default: op
  mhdftools.commands.pay:
    description: 转账
    default: true
  mhdftools.commands.randomteleport:
    description: 随机传送
    default: true
  mhdftools.commands.reply:
    description: 回复私聊
    default: true
  mhdftools.commands.sethome:
    description: 设置家
    default: true
  mhdftools.commands.setspawn:
    description: 设置出生点
    default: op
  mhdftools.commands.setwarp:
    description: 设置传送点
    default: op
  mhdftools.commands.spawn:
    description: 返回出生点
    default: true
  mhdftools.commands.stop:
    description: 更好的关服
    default: op
  mhdftools.commands.suicide:
    description: 自杀
    default: op
  mhdftools.commands.tpa:
    description: 请求传送到指定玩家位置
    default: true
  mhdftools.commands.tpahere:
    description: 请求指定玩家传送到当前位置
    default: true
  mhdftools.commands.tpback:
    description: 返回传送前的位置
    default: true
  mhdftools.commands.vanish:
    description: 隐身
    default: op
  mhdftools.commands.warp:
    description: 传送到指定传送点
    default: true
  mhdftools.commands.warp.other:
    description: 传送他人到指定传送点
    default: op