#调试模式
Debug: false

#检查更新
CheckVersion: true

#bStats https://bstats.org/plugin/bukkit/Cheng-Tools-Reloaded/17154
bStats: true

#数据存储设置
DataSettings:
  #存储类型(YAML, MySQL)
  Type: "YAML"
  #数据库地址
  Host: "127.0.0.1:3306"
  #数据库用户
  User: "root"
  #数据库密码
  Password: "root"
  #数据库
  Database: "MHDFTools"

#跨服模式
BungeecordSettings:
  #开关
  Enable: false

#垃圾桶设置
TrashSettings:
  #开关
  Enable: true
  #菜单配置
  GUISettings:
    #菜单类型(CHEST DISPENSER)
    Type: CHEST
    #菜单大小(仅限CHEST模式)
    Size: 9
    #菜单标题
    Title: "&b垃圾桶"

#右键打开末影箱设置
FastUseEnderChestSettings:
  #开关
  Enable: true

#右键打开潜影盒设置
FastUseShulkerBoxSettings:
  #开关
  Enable: true
  #潜影盒菜单标题
  MenuTitle: "&b快速使用-潜影盒"

#右键打开末影箱设置
FastUseCraftingTableSettings:
  #开关
  Enable: true

#隐身系统设置
VanishSettings:
  #开关
  Enable: true

#Spawn系统设置
SpawnSettings:
  #开关
  Enable: true
  #进服传送至Spawn位置
  JoinTeleport: false
  #复活自动传送至Spawn位置
  ReSpawnTeleport: false
  #Spawn系统服务器 跨服模式下必须配置
  Server: "无"
  #位置信息配置
  World: "world"
  X: 0.0
  Y: 3.0
  Z: 0.0
  Yaw: 90.0
  Pitch: 0.0

#玩家进入服务器发送欢迎消息
PlayerJoinSendMessageSettings:
  #开关
  Enable: true
  #消息
  Message: |-
    &b%PlayerName%&e欢迎加入服务器呀~
    &a服务器官方QQ群: 114514

#自定义玩家进入服务器提示
CustomJoinServerMessageSettings:
  #开关
  Enable: true
  #默认设置
  Default:
    #权重
    Weight: 0
    #玩家进入服务器的提示
    JoinMessage: "&a&l%PlayerName%&e&l加入了游戏"
  #拥有 MHDFTools.JoinMessage.<名字> 权限的人的提示
  #例: MHDFTools.JoinMessage.admin
  #组名字必须小写!
  admin:
    #权重
    Weight: 1
    #玩家进入服务器的提示
    JoinMessage: "&c&l%PlayerName%&e&l加入了游戏"

#自定义玩家退出服务器提示
CustomQuitServerMessageSettings:
  #开关
  Enable: true
  #默认设置
  Default:
    #权重
    Weight: 0
    #玩家退出服务器的提示
    QuitMessage: "&a&l%PlayerName%&e&l离开了游戏"
  #拥有 MHDFTools.QuitMessage.<名字> 权限的人的提示
  #例: MHDFTools.QuitMessage.admin
  #组名字必须小写!
  admin:
    #权重
    Weight: 1
    #玩家退出服务器的提示
    QuitMessage: "&c&l%PlayerName%&e&l离开了游戏"

#Tpa系统设置
TpaSettings:
  #开关
  Enable: true
  #超时时间
  OutTime: 60

#TpaHere系统设置
TpaHereSettings:
  #开关
  Enable: true
  #超时时间
  OutTime: 60

#经济系统设置
EconomySettings:
  #开关
  Enable: true
  #经济排行榜显示前几
  BalTopInt: 5
  #默认金钱数量
  InitialMoney: 1000.0
  #金钱名字
  MoneyName: "&e金币"

#超级List命令设置
SuperListSettings:
  #开关
  Enable: true
  #命令提示
  Message:
    - "&7-----------&6List系统&7-----------"
    - "&eTPS: %TPS_1% %TPS_5% %TPS_15%"
    - "&e内存占用: %mem_used%&7/&e%mem_max%"
    - "&e在线玩家: %online%/%max_online%"
    - "&e玩家列表:"
    - "&e%playerlist%"
    - "&7-----------&6List系统&7-----------"

#家系统设置
HomeSystemSettings:
  #开关
  Enable: true
  #一个玩家默认最多能创建多少个家
  #可以通过 MHDFTools.Home.<数量> 控制
  MaxHomeTime: 5
  #关闭世界列表
  DisableWorldList:
    - "pvp"

#登录系统设置
LoginSystemSettings:
  #开关
  Enable: true
  #密码最短长度限制
  MinPaswordLength: 6
  #密码最大长度限制
  MaxPaswordLength: 18
  #相同IP自动登录
  AutoLogin: true
  #过于简单的密码
  EasyPasswords:
    - "123456"
  #未登录允许使用的命令
  AllowUsedComamnds:
    - "/l"
    - "/login"
    - "/reg"
    - "/register"

#白名单系统
WhiteListSettings:
  #开关
  Enable: false
  #拥有指定权限即可进入
  Permission: "MHDFTools.Whitelist"
  #踢出提示
  KickMessage: |-
    &b梦回东方-工具
    &c您没有白名单
  #白名单列表
  List:
    - "qwq"

#禁用命令设置
BanCommandSettings:
  #开关
  Enable: true
  #OP免疫
  OpBypass: false
  #禁用命令列表
  BanCommandList:
    - plugins
    - bukkit:plugins
    - pl
    - bukkit:pl
    - ver
    - version
    - bukkit:ver
    - bukkit:version
  #使用被禁用的命令提示
  UsedBanCommandMessage:
    - "&c这个命令不存在,请重试!"

#超级Stop命令设置
SuperStopSettings:
  #开关
  Enable: true
  #关服提示格式
  StopMessageFormat: |-
    &b梦回东方-工具
    {Message}
  #默认关服提示
  DefaultStopMessage: |-
    &c服务器已关闭

#MOTD系统设置
MOTDSettings:
  #开关
  Enable: true
  #最大玩家数
  MaxPlayers: 5835
  #最大玩家数
  Line1: "&bMHDFTools"
  Line2: "&6HelloWorld!"

#计分板系统设置
ScoreboardSettings:
  #开关
  Enable: true
  #标题
  Title: "&b梦回东方-工具"
  #内容
  Lines:
    - "&e&l欢迎%player_name%"
    - "&e&lqwq"
    - "&e&lawa"

#命令映射
CommandLinkSettings:
  #开关
  Enable: true
  #命令列表
  CommandList:
    #自定义命名
    添加权限:
      #仅玩家执行
      OnlyPlayer: false
      #使用BCAPI获取玩家列表
      BungeeCordGetPlayerList: false
      #必须拥有指定权限
      Permission: "MHDFTools.CommandLink.添加权限"
      #Tab补全列表功能
      TabList:
        #参数1的TAB补全
        1:
          - "{PlayerList}"
        #参数2的TAB补全
        2:
          - "你不会用吗?"
      #参数数量不同执行不同的命令
      #============================================
      #操作列表
      #[player]|<命令> #玩家执行命令
      #[consoleMessage]|<命令> #后台执行命令
      #[playsound]|<音频>|<音量|<音效> #播放音频
      #[playsound_pack]|<音频>|<音量|<音效> #播放资源包音频
      #[message]|<消息第一行>|<消息第二行> #发送消息
      #[broadcast]|<消息第一行>|<消息第二行> #发送所有人可见的消息
      #[title]|<消息第一行>|<消息第二行>|淡出时间|停留时间|淡出时间 #发送标题消息
      #[actionbar]|<消息> #发送ActionBar消息
      #============================================
      ActionList:
        #有两个参数时执行的操作
        2:
          - "[player]|lp user %1 perm set %2"
        #默认操作
        Default:
          - "[message]|&c命令错误,正确格式:/添加权限 <玩家ID> <权限>"

#事件操作
EventActionSettings:
  #开关
  Enable: true
  #事件列表
  EventList:
    #自定义命名
    玩家加入:
      #============================================
      #事件类型
      #玩家加入服务器
      #玩家退出服务器
      #玩家切换世界
      #玩家聊天
      #玩家死亡
      #玩家复活
      #玩家移动
      #玩家传送
      #玩家破坏方块
      #玩家放置方块
      #============================================
      Event: "玩家加入服务器"
      #仅限指定世界可用列表(仅 玩家切换世界 事件)
      #WorldList:
      #  - "world"
      #============================================
      #操作列表
      #[player]|<命令> #玩家执行命令
      #[consoleMessage]|<命令> #后台执行命令
      #[playsound]|<音频>|<音量|<音效> #播放音频
      #[playsound_pack]|<音频>|<音量|<音效> #播放资源包音频
      #[message]|<消息第一行>|<消息第二行> #发送消息
      #[broadcast]|<消息第一行>|<消息第二行> #发送所有人可见的消息
      #[title]|<消息第一行>|<消息第二行>|淡出时间|停留时间|淡出时间 #发送标题消息
      #[actionbar]|<消息> #发送ActionBar消息
      #[teleport]|<World>|<X>|<Y>|<Z>|<Yaw>|<Pitch> #传送玩家至指定坐标
      #============================================
      ActionList:
        - "[message]|&e你知道吗,事件操作系统很好用的!"

#时间操作
TimeActionSettings:
  #开关
  Enable: true
  #定时任务
  ActionList:
    #自定义命名
    定时操作:
      #============================================
      #时间类型
      #定时操作 #每多久操作一次
      #定点操作 #指定时间操作一次
      #============================================
      Type: "定时操作"
      #时间设置 (格式: 时:分:秒)
      Time: "0:0:15"
      #============================================
      #操作列表
      #[player]|<命令> #玩家执行命令
      #[consoleMessage]|<命令> #后台执行命令
      #[playsound]|<音频>|<音量|<音效> #播放音频
      #[playsound_pack]|<音频>|<音量|<音效> #播放资源包音频
      #[message]|<消息第一行>|<消息第二行> #发送消息
      #[broadcast]|<消息第一行>|<消息第二行> #发送所有人可见的消息
      #[title]|<消息第一行>|<消息第二行>|淡出时间|停留时间|淡出时间 #发送标题消息
      #[actionbar]|<消息> #发送ActionBar消息
      #[teleport]|<World>|<X>|<Y>|<Z>|<Yaw>|<Pitch> #传送玩家至指定坐标
      #============================================
      ActionList:
        - "[broadcast]|&e感谢您使用MHDF-Tools!"
    #自定义命名
    定点操作:
      #============================================
      #时间类型
      #定时操作 #每多久操作一次
      #定点操作 #指定时间操作一次
      #============================================
      Type: "定点操作"
      #时间设置 (格式: 时:分:秒)
      Time: "12:0:0"
      #============================================
      #操作列表
      #[player]|<命令> #玩家执行命令
      #[consoleMessage]|<命令> #后台执行命令
      #[playsound]|<音频>|<音量|<音效> #播放音频
      #[playsound_pack]|<音频>|<音量|<音效> #播放资源包音频
      #[message]|<消息第一行>|<消息第二行> #发送消息
      #[broadcast]|<消息第一行>|<消息第二行> #发送所有人可见的消息
      #[title]|<消息第一行>|<消息第二行>|淡出时间|停留时间|淡出时间 #发送标题消息
      #[actionbar]|<消息> #发送ActionBar消息
      #[teleport]|<World>|<X>|<Y>|<Z>|<Yaw>|<Pitch> #传送玩家至指定坐标
      #============================================
      ActionList:
        - "[broadcast]|&e中午12点啦!快去吃饭,不吃饭我就生气了,哼!"

#Back系统设置
BackSettings:
  #开关
  Enable: true
  #延迟
  Delay: 3
  #关闭世界列表
  DisableWorldList:
    - "pvp"

#TpBack系统设置
TpBackSettings:
  #开关
  Enable: true
  #延迟
  Delay: 3
  #关闭世界列表
  DisableWorldList:
    - "pvp"

#飞行系统设置
FlySettings:
  #开关
  Enable: true
  #当开启飞行时触发指定事件自动重新启用飞行
  AutoOpenSettings:
    #切换世界时
    ChangeWorld: true
    #重生
    ReSpawn: true
    #重新加入
    ReJoin: true
  #禁止使用飞行系统世界列表
  AntiFlyWorldList:
    - "boss"

#更简单的游戏模式设置
EasyGamemodeSettings:
  #开关
  Enable: true

#Invsee系统设置
InvseeSettings:
  #开关
  Enable: true

#帽子系统设置
HatSettings:
  #开关
  Enable: true

#快速晴天命令设置
FastSunSettings:
  #开关
  Enable: true

#快速调时间命令设置
FastSetTimeSettings:
  #开关
  Enable: true

#查询玩家IP与IP归属地命令设置
IpSettings:
  #开关
  Enable: true

#菜单系统开关设置
MenuSettings:
  #开关
  Enable: true

#让玩家转头系统的开关设置
RotateSettings:
  #开关
  Enable: true

#返回床位置设置
BedSettings:
  #开关
  Enable: true

#改名系统设置
#PAPI变量: %MHDFTools_Nick%
NickSettings:
  #开关
  Enable: true
  #最小长度
  MinLength: 3
  #最大长度
  MaxLength: 16
  #禁止设置服务器玩家内的名字
  AntiSetPlayerName: true
  #禁止包含的词汇
  BlackWordList:
    - "腐竹"
    - "服主"
    - "管理"
    - "傻逼"
    - "sb"

#聊天颜色设置
ChatColorSettings:
  #开关
  Enable: true
  #分组管理
  Group:
    #默认设置
    Default:
      #权重
      Weight: 0
      #聊天颜色
      ChatColor: "&7"
    #拥有 MHDFTools.ChatColor.<名字> 权限的组的颜色
    #例: MHDFTools.ChatColor.admin
    #组名字必须小写!
    admin:
      #权重
      Weight: 1
      #聊天颜色
      ChatColor: "&c"

#地标设置
WarpSettings:
  #开关
  Enable: true
  #关闭世界列表
  DisableWorldList:
    - "pvp"

#回复饱食度设置
FeedSettings:
  #开关
  Enable: true

#治疗设置
HealSettings:
  #开关
  Enable: true

#修复手上物品设置
RepairSettings:
  #开关
  Enable: true

#自杀设置
SuicideSettings:
  #开关
  Enable: true

#强制执行命令设置
SudoSettings:
  #开关
  Enable: true

#全服消息命令设置
SaySettings:
  #开关
  Enable: true

#冻结玩家设置
FreezeSettings:
  #开关
  Enable: true
  #是否在玩家退出游戏后进行惩罚
  PunishEnable: true
  #当玩家拥有这个权限后，那么它将不会被冻结
  Bypass: "MHDFTools.Bypass.Freeze"
  #处罚的命令
  #%player_name% 玩家id
  #%player_ip% 玩家ip
  PunishCommand: "litebans:banip %player_ip% &eMHDFTools &7| &eUnfair Advantage &7[&c拒绝查端 ID= %player_name% &7] --sender=MHDFTools"